# -*- coding: utf-8 -*-
"""2026 iGEM dry lab data fetching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfHCNcoLrHBgTk9cH3lfpn2lOfD0LKs_
"""

# pip install biopython

from Bio import Entrez
import pandas as pd
import time

# --- 1. 基本設定 ---
# 務必填寫 email，否則 NCBI 會擋下你的請求
Entrez.email = "cchen29@cmc.edu"

# --- 2. 修正後的黃金查詢字串 ---
# 邏輯：(包含Xanthomonas) AND (包含phage或bacteriophage) AND (包含complete genome) AND (必須是病毒)
search_query = '("Xanthomonas"[All Fields] AND ("phage"[All Fields] OR "bacteriophage"[All Fields]) AND "complete genome"[All Fields] AND "Viruses"[Organism])'

def generate_accession_list(query):
    print(f"正在 NCBI Nucleotide 執行搜尋...\n關鍵字: {query}")

    # 發送搜尋請求 (最多抓取 1000 筆，通常 Xanthomonas 噬菌體大約幾百個)
    try:
        search_handle = Entrez.esearch(db="nucleotide", term=query, retmax=1000)
        search_record = Entrez.read(search_handle)
        id_list = search_record["IdList"]
        search_handle.close()
    except Exception as e:
        print(f"搜尋失敗: {e}")
        return []

    total_found = len(id_list)
    print(f"成功找到 {total_found} 個潛在的噬菌體 ID！正在下載摘要資料...")

    results = []

    # 如果有找到資料，批次獲取摘要 (每次抓 200 筆，避免超載)
    if total_found > 0:
        batch_size = 200
        for start in range(0, total_found, batch_size):
            end = min(total_found, start + batch_size)
            batch_ids = id_list[start:end]

            print(f"處理進度: {start+1} 到 {end}...")

            try:
                summary_handle = Entrez.esummary(db="nucleotide", id=",".join(batch_ids))
                summaries = Entrez.read(summary_handle)
                summary_handle.close()

                for item in summaries:
                    results.append({
                        "Accession": item["Caption"],      # 這是你要的 MG944227 等 ID
                        "Description": item["Title"],      # 標題通常包含 Phage 名稱
                        "Length": item["Length"],          # 基因組長度 (可藉此過濾掉太短的片段)
                        "UpdateDate": item["UpdateDate"]   # 了解這是不是最新的資料
                    })
            except Exception as e:
                print(f"獲取摘要時發生錯誤: {e}")

            # 禮貌性延遲，保護你的 IP 不被 NCBI 封鎖
            time.sleep(1)

    return results

# --- 3. 執行並輸出成 Excel 友善的 CSV ---
phage_list = generate_accession_list(search_query)

if phage_list:
    df = pd.DataFrame(phage_list)

    # 進階過濾：通常完整的噬菌體基因組大於 10,000 bp (10kb)
    # 這樣可以進一步濾掉一些被誤標為 complete genome 的小質體或片段
    df = df[df['Length'] > 10000]

    output_filename = "xanthomonas_phages_accession_list.csv"
    df.to_csv(output_filename, index=False, encoding='utf-8-sig') # utf-8-sig 讓 Excel 繁體中文不亂碼
    print(f"\n大功告成！過濾後共產出 {len(df)} 筆完整基因組資料。")
    print(f"檔案已儲存為: {output_filename}")
else:
    print("未能抓取到任何資料，請檢查網路連線或查詢字串。")

# pip install pandas biopython

import pandas as pd
from Bio import Entrez, SeqIO
import time
import os

# --- 1. 基本設定 ---
# 務必填寫 email，否則大量請求會被 NCBI 阻擋
Entrez.email = "cchen29@cmc.edu"
input_csv = "xanthomonas_phages_accession_list.csv"
output_csv = "phage_host_matrix_raw.csv"

# --- 2. 讀取你剛剛生成的清單 ---
print(f"正在讀取 {input_csv} ...")
df = pd.read_csv(input_csv)
accession_list = df['Accession'].tolist()
total_ids = len(accession_list)
print(f"共載入 {total_ids} 個 Accession IDs，準備開始向 NCBI 爬取宿主資料。\n")

# --- 3. 批次爬取函數 ---
def fetch_host_batch(id_batch):
    # 將一個 batch (例如 50 個 ID) 組合為字串 "ID1,ID2,ID3..." 進行一次性查詢，這比一個個查快 50 倍
    query_ids = ",".join(id_batch)
    results = []

    try:
        # 請求下載 GenBank 格式
        handle = Entrez.efetch(db="nucleotide", id=query_ids, rettype="gb", retmode="text")
        records = list(SeqIO.parse(handle, "genbank"))
        handle.close()

        for record in records:
            phage_name = record.description
            acc_id = record.id
            host = "Unknown" # 預設值

            # 在 GenBank 格式的 features 中尋找 source 標籤
            for feature in record.features:
                if feature.type == "source":
                    # 嘗試抓取 host 或 lab_host
                    host_info = feature.qualifiers.get("host", feature.qualifiers.get("lab_host", ["Unknown"]))
                    host = host_info[0] if host_info else "Unknown"
                    break

            results.append({
                "Phage": phage_name,
                "Accession": acc_id,
                "Host": host,
                "Affinity": 1 if host != "Unknown" else "", # NCBI 記錄的都是有感染能力的 (Affinity = 1)
                "Source": f"NCBI: {acc_id}"
            })

    except Exception as e:
        print(f"批次下載發生錯誤: {e}")
        # 如果整批失敗，就記錄為 Error 方便事後除錯
        for acc in id_batch:
            results.append({"Phage": "ERROR", "Accession": acc, "Host": "ERROR", "Affinity": "", "Source": "ERROR"})

    return results

# --- 4. 執行批次下載與進度條 ---
batch_size = 50 # 每次向 NCBI 請求 50 筆資料 (太大会 Timeout)
all_results = []

for i in range(0, total_ids, batch_size):
    batch = accession_list[i : i + batch_size]
    print(f"正在爬取進度: {i + 1} ~ {min(i + batch_size, total_ids)} / {total_ids} ...")

    batch_data = fetch_host_batch(batch)
    all_results.extend(batch_data)

    # 禮貌性延遲，保護 IP
    time.sleep(1.5)

# --- 5. 輸出最終矩陣 ---
final_df = pd.DataFrame(all_results)
final_df.to_csv(output_csv, index=False, encoding='utf-8-sig')
print(f"\n大功告成！已成功生成初步的感染矩陣並儲存為: {output_csv}")

import pandas as pd
from Bio import Entrez, SeqIO
import time

# --- 1. 基本設定 ---
Entrez.email = "cchen29@cmc.edu"
input_csv = "xanthomonas_phages_accession_list.csv"
output_csv = "phage_host_matrix_with_ids.csv"

# 建立一個「快取字典」，避免重複查詢相同的宿主 ID
host_id_cache = {"Unknown": "Unknown"}

# --- 2. 輔助函數：根據細菌名稱，尋找最具代表性的 Accession ID ---
def get_host_accession(host_name):
    # 如果這個細菌我們已經查過了，直接從記憶裡拿出來
    if host_name in host_id_cache:
        return host_id_cache[host_name]

    print(f"  🔍 發現新宿主 '{host_name}'，正在尋找其代表性 Accession ID...")

    # 搜尋條件：找這個細菌的「完整基因組」，並且最好是 RefSeq (官方參考序列)
    # 加上 srcdb_refseq[PROP] 可以優先找到 NC_ 開頭的高品質序列
    query = f'"{host_name}"[Organism] AND "complete genome"[All Fields] AND srcdb_refseq[PROP]'

    try:
        search_handle = Entrez.esearch(db="nucleotide", term=query, retmax=1)
        search_record = Entrez.read(search_handle)
        search_handle.close()

        id_list = search_record["IdList"]

        if id_list:
            # 如果有找到 UID，再轉換成我們常見的 Accession ID (NC_xxxx 或 NZ_xxxx)
            summary_handle = Entrez.esummary(db="nucleotide", id=id_list[0])
            summary_record = Entrez.read(summary_handle)
            summary_handle.close()

            host_acc = summary_record[0]["Caption"]
            host_id_cache[host_name] = host_acc # 存入快取
            return host_acc
        else:
            # 如果加上 RefSeq 找不到，放寬條件再找一次
            fallback_query = f'"{host_name}"[Organism] AND "complete genome"[All Fields]'
            fallback_handle = Entrez.esearch(db="nucleotide", term=fallback_query, retmax=1)
            fallback_record = Entrez.read(fallback_handle)
            fallback_handle.close()

            if fallback_record["IdList"]:
                sum_handle = Entrez.esummary(db="nucleotide", id=fallback_record["IdList"][0])
                sum_rec = Entrez.read(sum_handle)
                sum_handle.close()
                host_acc = sum_rec[0]["Caption"]
                host_id_cache[host_name] = host_acc
                return host_acc
            else:
                host_id_cache[host_name] = "No Complete Genome Found"
                return "No Complete Genome Found"

    except Exception as e:
        print(f"  ❌ 尋找宿主 ID 時發生錯誤: {e}")
        return "ERROR"
    finally:
        time.sleep(0.5) # 避免請求過快

# --- 3. 讀取與核心批次爬取函數 ---
print(f"正在讀取 {input_csv} ...")
df = pd.read_csv(input_csv)
accession_list = df['Accession'].tolist()
total_ids = len(accession_list)

def fetch_phage_and_host_data(id_batch):
    query_ids = ",".join(id_batch)
    results = []

    try:
        handle = Entrez.efetch(db="nucleotide", id=query_ids, rettype="gb", retmode="text")
        records = list(SeqIO.parse(handle, "genbank"))
        handle.close()

        for record in records:
            phage_name = record.description
            acc_id = record.id
            host_name = "Unknown"

            for feature in record.features:
                if feature.type == "source":
                    host_info = feature.qualifiers.get("host", feature.qualifiers.get("lab_host", ["Unknown"]))
                    host_name = host_info[0] if host_info else "Unknown"
                    break

            # 呼叫輔助函數，獲取 Host 的 Accession ID
            host_acc_id = get_host_accession(host_name)

            results.append({
                "Phage": phage_name,
                "Phage_Accession": acc_id,
                "Host_Name": host_name,
                "Host_Accession": host_acc_id,
                "Affinity": 1 if host_name != "Unknown" else "",
                "Source": f"NCBI: {acc_id}"
            })

    except Exception as e:
        print(f"批次下載發生錯誤: {e}")
    return results

# --- 4. 執行迴圈 ---
batch_size = 50
all_results = []

for i in range(0, total_ids, batch_size):
    batch = accession_list[i : i + batch_size]
    print(f"\n▶ 正在爬取 Phage 批次: {i + 1} ~ {min(i + batch_size, total_ids)} / {total_ids}")

    batch_data = fetch_phage_and_host_data(batch)
    all_results.extend(batch_data)
    time.sleep(1)

# --- 5. 輸出結果 ---
final_df = pd.DataFrame(all_results)
final_df.to_csv(output_csv, index=False, encoding='utf-8-sig')
print(f"\n大功告成！已成功生成包含 Host ID 的感染矩陣並儲存為: {output_csv}")

'''
import pandas as pd
import numpy as np

# --- 1. 讀取你爬取下來的「長格式」資料 ---
input_file = "phage_host_matrix_with_ids.csv"
output_matrix_file = "final_interaction_matrix.csv"

print(f"正在讀取原始資料：{input_file}")
df_raw = pd.read_csv(input_file)

# 為了確保矩陣乾淨，我們排除那些 Host 還是 Unknown 或 Error 的無效資料
df_clean = df_raw[~df_raw['Host_Name'].isin(['Unknown', 'ERROR', 'No Complete Genome Found'])]

# 假設你有些資料有明確標示不感染 (0)，有些標示感染 (1)
# 確保 Affinity 欄位是數字型態
df_clean['Affinity'] = pd.to_numeric(df_clean['Affinity'], errors='coerce')

# --- 2. 核心魔法：使用 pivot_table 轉換成矩陣 ---
print("正在轉換為 2D 感染矩陣 (Pivot Table)...")

# index = 矩陣的 Rows (噬菌體)
# columns = 矩陣的 Columns (宿主細菌)
# values = 填入格子裡的值 (感染能力)
matrix_df = df_clean.pivot_table(
    index='Phage',
    columns='Host_Name',
    values='Affinity',
    aggfunc='max' # 如果同一隻 Phage 對同一個 Host 有兩筆資料，取最大值 (只要有 1 就算感染)
)

# --- 3. 處理未測試 (Untested) 的空值 ---
# 在 pandas 的 pivot_table 中，如果 Phage 和 Host 之間沒有資料對應，
# 預設就會自動變成 NaN (即 numpy 的 np.nan)。
# 這剛好完美符合你「不確定的 affinity 請填 np.nan」的需求！

# （選用）如果你想把欄位名稱排個序，讓矩陣看起來更整齊
matrix_df = matrix_df.sort_index(axis=0).sort_index(axis=1)

# --- 4. 輸出最終矩陣 ---
matrix_df.to_csv(output_matrix_file, encoding='utf-8-sig')
print(f"\n矩陣生成成功！已儲存為：{output_matrix_file}")

# 印出左上角的一小塊讓你看預覽
print("\n=== 矩陣預覽 (Top 5 Phages) ===")
print(matrix_df.head())

len(matrix_df)

'''

import pandas as pd
import numpy as np

# --- 1. 读取原始数据 ---
input_file = "phage_host_matrix_with_ids.csv"
output_matrix_file = "final_interaction_matrix.csv"

print(f"正在读取原始资料：{input_file}")
df_raw = pd.read_csv(input_file)

# 清理无效资料
df_clean = df_raw[~df_raw['Host_Name'].isin(['Unknown', 'ERROR', 'No Complete Genome Found'])].copy()
df_clean['Affinity'] = pd.to_numeric(df_clean['Affinity'], errors='coerce')

# --- 2. 建立 Phage 的「名称 + Accession」复合标签（用于行） ---
df_clean['Phage_Label'] = df_clean['Phage'] + ' [' + df_clean['Phage_Accession'] + ']'

# --- 3. Pivot Table（用复合标签作为行） ---
print("正在转换为 2D 感染矩阵...")
matrix_df = df_clean.pivot_table(
    index='Phage_Label',
    columns='Host_Name',
    values='Affinity',
    aggfunc='max'
)
matrix_df = matrix_df.sort_index(axis=0).sort_index(axis=1)

# --- 4. 在列标题加入 Host Accession ---
# 建立 Host_Name -> Host_Accession 的对应字典
host_acc_map = (
    df_clean[['Host_Name', 'Host_Accession']]
    .drop_duplicates()
    .set_index('Host_Name')['Host_Accession']
    .to_dict()
)

# 把矩阵的列名替换成「Host_Name [Host_Accession]」格式
matrix_df.columns = [
    f"{host} [{host_acc_map.get(host, 'N/A')}]"
    for host in matrix_df.columns
]

# 把行的 index 名称改得更清楚
matrix_df.index.name = 'Phage [Phage_Accession]'

# --- 5. 输出 ---
matrix_df.to_csv(output_matrix_file, encoding='utf-8-sig')
print(f"\n矩阵生成成功！已儲存為：{output_matrix_file}")

print("\n=== 矩阵预览 (Top 5 Phages) ===")
print(matrix_df.head())
print(f"\n矩阵大小：{matrix_df.shape[0]} 噬菌体 x {matrix_df.shape[1]} 宿主")